name: phonepe
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker:
  carousel_slider: any
  url_launcher: ^5.0.2
  intl: ^0.15.7
  fluttertoast: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/phonepay/
    - assets/phonepay/banking.png
    - assets/phonepay/ic_menu_balance_selected.png
    - assets/phonepay/ic_menu_invite.png
    - assets/phonepay/ic_menu_receive_selected.png
    - assets/phonepay/ic_radiofocused.png
    - assets/phonepay/notifications.png
    - assets/phonepay/outline_account_circle.png
    - assets/phonepay/outline_help.png
    - assets/phonepay/outline_qrscan.png
    - assets/phonepay/placeholder_contact_provider.png
    - assets/phonepay/request_money.png
    - assets/phonepay/suggestions_strip.png
    - assets/phonepay/logo.png
    - assets/phonepay/powered_by.png
    - assets/phonepay/recharge.png
    - assets/phonepay/dth.png
    - assets/phonepay/electricity.png
    - assets/phonepay/creditcard.png
    - assets/phonepay/gas.png
    - assets/phonepay/postpaid.png
    - assets/phonepay/landline.png
    - assets/phonepay/broadband.png
    - assets/phonepay/water.png
    - assets/phonepay/datacard.png
    - assets/phonepay/insurance.png
    - assets/phonepay/muncipaltax.png
    - assets/phonepay/history.png
    - assets/phonepay/stores.png
    - assets/phonepay/placeholder.png
    - assets/phonepay/rupee.png
    - assets/phonepay/newgiftcard.png
    - assets/phonepay/right-arrow.png
    - assets/ghghgh.jpg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
